# Generated by Django 4.1 on 2024-02-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=50)),
                ('categorydesc', models.CharField(max_length=150)),
                ('categoryphoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
