# Generated by Django 4.1 on 2024-02-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_subcategory',
            fields=[
                ('subcategoryid', models.AutoField(primary_key=True, serialize=False)),
                ('subcategoryname', models.CharField(max_length=50)),
                ('subcategorydesc', models.CharField(max_length=150)),
                ('subcategoryphoto', models.ImageField(upload_to='')),
            ],
        ),
    ]
