# Generated by Django 4.1 on 2024-02-23 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_tbl_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_subcategory',
            name='categoryid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.tbl_category'),
        ),
    ]
