# Generated by Django 4.1 on 2024-03-15 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_tbl_subcategory_categoryid'),
        ('company', '0003_alter_tbl_comproduct_comprdprice'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shopproduct',
            fields=[
                ('shopproductid', models.AutoField(primary_key=True, serialize=False)),
                ('shopproductname', models.CharField(max_length=50)),
                ('shopproductdesc', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('regdate', models.DateField(default=datetime.date.today)),
                ('categoryid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.tbl_category')),
                ('shopid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.tbl_shop')),
                ('subcategoryid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.tbl_subcategory')),
                ('unitid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.tbl_unit')),
            ],
        ),
    ]
