# Generated by Django 4.1 on 2024-03-18 14:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_tbl_comproduct_comprdprice'),
        ('shop', '0002_tbl_shopproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cprdrequest',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('regdate', models.DateField(default=datetime.date.today)),
                ('companyid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.tbl_company')),
                ('comproductid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.tbl_comproduct')),
                ('shopid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.tbl_shop')),
                ('unitid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.tbl_unit')),
            ],
        ),
    ]
