# Generated by Django 4.1 on 2024-03-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_tbl_cprdrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_selectedprd',
            fields=[
                ('selectid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('shopid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.tbl_shop')),
                ('shopproductid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.tbl_shopproduct')),
            ],
        ),
    ]
