# Generated by Django 4.1 on 2024-03-21 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_tbl_selectedprd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_selectedprd',
            name='status',
        ),
        migrations.AddField(
            model_name='tbl_selectedprd',
            name='regdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
