# Generated by Django 4.1 on 2024-03-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_tbl_selectedprd_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_selectedprd',
            name='regdate',
        ),
        migrations.AddField(
            model_name='tbl_selectedprd',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
