# Generated by Django 4.1 on 2024-03-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_tbl_billdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_selectedprd',
            old_name='status',
            new_name='sstatus',
        ),
    ]
