# Generated by Django 4.1 on 2024-03-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_status_tbl_selectedprd_sstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_billmaster',
            name='companyid',
        ),
        migrations.RemoveField(
            model_name='tbl_billmaster',
            name='shopid',
        ),
        migrations.RenameField(
            model_name='tbl_selectedprd',
            old_name='sstatus',
            new_name='status',
        ),
        migrations.DeleteModel(
            name='tbl_billdetails',
        ),
        migrations.DeleteModel(
            name='tbl_billmaster',
        ),
    ]
