# Generated by Django 4.1 on 2024-03-21 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_tbl_billmaster_companyid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_salesmaster',
            fields=[
                ('salesid', models.AutoField(primary_key=True, serialize=False)),
                ('totalprice', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('salesdate', models.DateField(default=datetime.date.today)),
                ('shopid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.tbl_shop')),
            ],
        ),
    ]
