# Generated by Django 4.1 on 2024-03-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_delete_tbl_billmaster'),
        ('shop', '0011_tbl_salesmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_salesdetails',
            fields=[
                ('salesdetailid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('salesid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.tbl_salesmaster')),
                ('shopproductid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.tbl_shopproduct')),
                ('unitid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.tbl_unit')),
            ],
        ),
    ]
