# Generated by Django 4.1 on 2024-02-26 10:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0005_tbl_subcategory_categoryid'),
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=50)),
                ('regno', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('regdate', models.DateField(default=datetime.date.today)),
                ('locationid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin.tbl_location')),
                ('loginid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guest.tbl_login')),
            ],
        ),
    ]
