# Generated by Django 4.1 on 2024-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_tbl_unit_tbl_comproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_comproduct',
            name='comprdprice',
            field=models.IntegerField(),
        ),
    ]
