# Generated by Django 4.1 on 2024-03-21 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_tbl_comproduct_comprdprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_billmaster',
            fields=[
                ('billid', models.AutoField(primary_key=True, serialize=False)),
                ('totalprice', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('confirmeddate', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.tbl_company')),
            ],
        ),
    ]
