# Generated by Django 4.1 on 2024-03-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_tbl_billmaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_billmaster',
        ),
    ]
